# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: backend check
      run: npm i && npm run test
      working-directory: backend
      
    - name: frontend check
      run: npm i && npm run test
      working-directory: frontend
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: 03b64d6b-40ee-4dc2-badf-db45b4d23dc0
        flags: unit-test
